version: '3.8'

services:
  telegram-bot:
    build: .
    env_file:
      - .env   # так docker-compose подтянет твои токены
    volumes:
      - ./logs:/app/logs  # только логи, чтобы не затереть код
    restart: unless-stopped
    ports:
      - "8000:8000"
