version: '3.8'

services:
  telegram-bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN
      - ADMIN_CHAT_ID
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    ports:
      - "8000:8000"
